### ISSUE TITLE
Reload server insider container

### ISSUE THREAD

**Issue by ilbassa** [payloadcms/template-blank#1]
I have launched
`npm create-payload-app`
and then
`docker-compose up`

When I make changes to the file (add a collection for example) how I can restart the server inside the container?

**Comment by jacobsfletch** [comment]
Hey @ilbassa! Are you still having troubles with this? I'm going to close this issue out now but feel free to keep the conversation going either as a [GitHub Discussion](https://github.com/payloadcms/payload/discussions) or on [Discord](https://discord.com/invite/payload).

**Comment by jacobsfletch** [comment]
Hey @ilbassa! Are you still having troubles with this? This repo will soon be archived because it's been merged into the main Payload repo here: https://github.com/payloadcms/payload/tree/master/templates/blank. I'm going to close this issue out now but feel free to keep the conversation going either as a [GitHub Discussion](https://github.com/payloadcms/payload/discussions) or on [Discord](https://discord.com/invite/payload).
